### ISSUE TITLE
Morpheus v5.4.4 buildVersion key error

### ISSUE THREAD

**Issue by lukelloydagi** [tryfan/python-morpheus-cypher#13]
I am getting the below error on a task:

`Task Execution Failed on Attempt 1
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "/var/opt/morpheus/morpheus-ui/workspace/py-a225f818-37d2-4cb0-afcf-a586d8900b7c/lib/python3.8/site-packages/morpheuscypher/__init__.py", line 85, in __init__
    self.set_cypher_endpoint()
  File "/var/opt/morpheus/morpheus-ui/workspace/py-a225f818-37d2-4cb0-afcf-a586d8900b7c/lib/python3.8/site-packages/morpheuscypher/__init__.py", line 103, in set_cypher_endpoint
    if LooseVersion(data['buildVersion']) < LooseVersion('5.3.3'):
KeyError: 'buildVersion'`

What is odd is that I have the same task running in two different Morpheus environments (both v5.4.4) but I am only getting the error in one of the environments 🤷‍♀️

**Comment by tryfan** [comment]
I think you may have an authentication error.  Recently, Morpheus required authentication to check the application version.  I should catch that and spit out a better error, but that's the error you'll receive if the `buildVersion` isn't returned from `/api/ping`

**Comment by lukelloydagi** [comment]
I am using the same code and (latest) morpheus-cypher in both environments. The error is from the morpheus-cypher module. The only difference between the two environments is one is a single VM (where it's working) while the other is a three node HA deployment (where it's not working).

**Comment by tryfan** [comment]
In `morpheuscypher/__init__.py` can you add the following lines above line 103 and post the result:
```
from pprint import pprint
pprint(data)
```

**Comment by lukelloydagi** [comment]
Not able to because I am using this in a Morpheus task so Morpheus will create the Python venv, pip install, run task and then clear venv

**Comment by lukelloydagi** [comment]
Sure, see below/attached.
No not defining the API key manually.

![script1](https://user-images.githubusercontent.com/91117653/160394936-8c73d824-c84c-4a94-88f1-ed67686d8329.PNG)
![script2](https://user-images.githubusercontent.com/91117653/160394939-d7b31abd-8372-42ef-abcd-f670befbf7c6.PNG)
![morpheus_task_additional_packages](https://user-images.githubusercontent.com/91117653/160395002-6af313bb-60a0-4ba1-ba67-58595811b52b.PNG)

**Comment by tryfan** [comment]
I uploaded a version with the print lines above.  You can use this URL in additional packages in a task: https://morphtest-tenant-bucket.s3.amazonaws.com/morpheus-cypher-0.1.4-1.tar.gz  

It should just print out the return from the Morpheus `/api/ping` endpoint with authentication.  It should look like this for 5.4.4:
```
{
    "success": true,
    "buildVersion": "5.4.4"
}
```

My current theory is that you have an older version of the module installed for the `morpheus-local` user or the system itself.

**Comment by lukelloydagi** [comment]
In the working environment it does return:
![image](https://user-images.githubusercontent.com/91117653/160568835-c7ae8100-bfd6-4578-9928-4400e091397d.png)

While in the non working environment I get:
![image](https://user-images.githubusercontent.com/91117653/160569084-7c3238f8-ecd3-44a6-b521-95da1e129057.png)

Morpheus creates a new Python virtualenv and pip installs each package on each task run doesn't it so I am confused as to why there would be anything stale?

**Comment by tryfan** [comment]
Honestly, I'm grasping at straws because I'm expecting a return from the api we're not seeing.  The output here is interesting, though.  I've never seen the ephemeral token task token expire.  They should last a few minutes.  This shows me that it's not the plugin, but there may be something wrong with the environment.  Can you create a case with Morpheus and we can get support to take a look?

**Comment by tryfan** [comment]
It looks like this might be related to a different bug, related to building Python virtualenvs in HA environments.  Looks like it's usually a problem with how fast the shared storage is.  The ephemeral task token should last 20 minutes.  There's supposed to be a fix for the environment issue in Morpheus 5.4.5.  I'll close the issue here.
